data:
  random_state: 42
  test_size: 0.2
experiment_name: iris-classification
model:
  params:
    C: 3.6837966015988095
    max_iter: 351
    solver: lbfgs
  type: logistic_regression
run_name: optuna-best
version: optuna_best
